User-agent: *
Disallow: /aggiungi-notizia/upload
Disallow: /aggiungi-notizia/upload
Disallow: /aggiungi-notizia
Disallow: /endpointdoc
Disallow: /login/
Disallow: /login/logout
Disallow: /login
Disallow: /login/enter
Allow: /contatti/
Allow: /azienda/
Allow: /index/
Allow: /index
Allow: /azienda
Allow: /contatti
Allow: /note-legali/
Allow: /note-legali
Sitemap: http://www.damicicostruzioni.it/sitemap.xml

